apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: ${ROLE}
  name: ${ROLE}-tang-ka
spec:
  kernelArguments:
    - 'rd.neednet=1'
