apiVersion: v1
baseDomain: {{ domain }}
networking:
  networkType: {{ network_type }}
{%- if ':' in machine_cidr %}
  machineCIDR: {{ machine_cidr }}
  clusterNetworks:
  - cidr: fd01::/48
    hostPrefix: 64
  serviceNetwork:
  - fd02::/112
{%- else %}
  clusterNetworks:
  - cidr: 10.132.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
{%- endif %}
metadata:
  name: {{ cluster }}
compute:
- name: worker
  replicas: {{ workers }}
controlPlane:
  name: master
  replicas: {{ masters }}
platform:
  none: {}
{% if ca != None -%}
additionalTrustBundle: |
 {{ ca | replace('\n', '\n ') }}
{%- endif %}
{% if disconnected_url != None -%}
imageContentSources:
- mirrors:
  - {{ disconnected_url }}/{{ disconnected_prefix }}
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - {{ disconnected_url }}/{{ disconnected_prefix }}
  source: {{ disconnected_origin }}/ocp/release
{%- endif %}
