apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: blacklist-ipi-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
      - name: nodeip-configuration.service
        enabled: true
        contents: |
          [Unit]
          Description=Writes IP address configuration so that kubelet and crio services select a valid node IP
          Wants=network-online.target
          After=network-online.target ignition-firstboot-complete.service
          Before=kubelet.service crio.service
          [Service]
          Type=oneshot
          ExecStart=/bin/bash -c "if [[ $(hostname) == *localhost* ]]; then ;\
             REVERSE=$(dig -x $(hostname -I | cut -f1 -d\ ) +short) ;\
             HOSTNAME=${REVERSE::-1} ;\
             echo $HOSTNAME > /etc/hostname ;\
             nmcli general hostname $HOSTNAME ;\
             systemctl restart systemd-hostnamed ;\
             else echo Hostname properly set; exit 0 ; fi"
          [Install]
          WantedBy=multi-user.target
    storage:
      files:
        - contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/kubernetes/manifests/coredns.yaml
        - contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/kubernetes/manifests/keepalived.yaml
        - contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/kubernetes/manifests/mdns-publisher.yaml
