apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: blacklist-ipi-master
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
      - name: nodeip-configuration.service
        enabled: true
        contents: |
          [Unit]
          Description=Writes IP address configuration so that kubelet and crio services select a valid node IP
          Wants=network-online.target
          After=network-online.target ignition-firstboot-complete.service
          Before=kubelet.service crio.service
          [Service]
          Type=oneshot
          ExecStart=/bin/bash -c "if [[ $(hostname) != *localhost* ]] ; then exit 0 ; fi ;\
          	REVERSE=$(dig -x $(hostname -I | cut -f1 ) +short) ;\
          	HOSTNAME=$(basename -s . $REVERSE) ;\
          	echo $HOSTNAME >/etc/hostname ;\
          	hostnamectl set-hostname $HOSTNAME"
          [Install]
          WantedBy=multi-user.target
    storage:
      files:
        - contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/kubernetes/manifests/coredns.yaml
        - contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/kubernetes/manifests/keepalived.yaml
        - contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/kubernetes/manifests/mdns-publisher.yaml
